### PR TITLE
PowerShell container

### PR DESCRIPTION
**Pull request by mxplusb**
Added base PowerShell container with various tools for pipelines.

Signed-off-by: Mike Lloyd <mlloyd@pivotal.io>

### CODE REVIEW

**Comment by aminjam** [comment]
@mxplusb Can you help us understand why we need the powershell container?

**Comment by mxplusb** [comment]
@aminjam sure, it's for the vSphere pipeline, you can push and install the Bosh Agent, export the OVA from vSphere, and repackage it as a stemcell in PowerShell, so the base container is for Concourse, so it can perform all the PowerShell operations. Doing these operations in PowerShell is a more Windows-native method than doing it with Ruby. :)

**Comment by aminjam** [comment]
@mxplusb This sounds great! This PR is only adding the Dockerfile for powershell. If I understand this correctly, you are trying to talk to vcenter through powershell from linux containers. Can we include all of those features in this PR? I understand that this may still be a work-in-progress for you. We would like to get the full picture of the process before deciding to merge these changes.

**Comment by mxplusb** [comment]
@aminjam yeah, there are/will be more features that I am going to be adding for sure! However I need to make changes here and in [greenhouse-ci](https://github.com/cloudfoundry-incubator/greenhouse-ci) as well, so I need to start somewhere. This may not be the final Docker container, it may be a Windows Server Container instead, depending on whether or not VMware's PowerCLI functions as intended in PowerShell Core.

Might be worth adding a tag for `vsphere-feature` or something similar, since I don't have write access and I'll have to file a couple PRs. :)

**Comment by crawsible** [comment]
@mxplusb Are you still working on this and need a solution here, or did you work around it/stop working on it?

**Comment by crawsible** [comment]
@mxplusb and I chatted offline; he's good to close this.

**Pull request closed without merging**
